//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HajAndUmrah.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer_tbl()
        {
            this.Payment_tbl = new HashSet<Payment_tbl>();
            this.Service_tbl = new HashSet<Service_tbl>();
        }
    
        public int CustomerId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string Passport { get; set; }
        public string Designation { get; set; }
        public int Phone { get; set; }
        public int NoOfAdultTravellers { get; set; }
        public Nullable<int> NoOfChildTravellers { get; set; }
        public Nullable<int> TotalPrice { get; set; }
        public int PackageId { get; set; }
    
        public virtual Package_tbl Package_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment_tbl> Payment_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service_tbl> Service_tbl { get; set; }
    }
}
