//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HajAndUmrah.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HajAndUmrahDBEntities1 : DbContext
    {
        public HajAndUmrahDBEntities1()
            : base("name=HajAndUmrahDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin_tbl> Admin_tbl { get; set; }
        public virtual DbSet<Customer_tbl> Customer_tbl { get; set; }
        public virtual DbSet<HotelName_tbl> HotelName_tbl { get; set; }
        public virtual DbSet<Notification_tbl> Notification_tbl { get; set; }
        public virtual DbSet<Order_tbl> Order_tbl { get; set; }
        public virtual DbSet<Package_tbl> Package_tbl { get; set; }
        public virtual DbSet<PackageGroup_tbl> PackageGroup_tbl { get; set; }
        public virtual DbSet<PackageType_tbl> PackageType_tbl { get; set; }
        public virtual DbSet<Payment_tbl> Payment_tbl { get; set; }
        public virtual DbSet<RoomType_tbl> RoomType_tbl { get; set; }
        public virtual DbSet<StarRate_tbl> StarRate_tbl { get; set; }
        public virtual DbSet<TravelClass_tbl> TravelClass_tbl { get; set; }
        public virtual DbSet<Service_tbl> Service_tbl { get; set; }
    }
}
