//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HajAndUmrah.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Package_tbl()
        {
            this.Customer_tbl = new HashSet<Customer_tbl>();
        }
    
        public int PackageId { get; set; }
        public System.DateTime Date { get; set; }
        public string PackageName { get; set; }
        public int PackageType { get; set; }
        public int PackageGroup { get; set; }
        public int NoOfDays { get; set; }
        public int TravelClass { get; set; }
        public int HotelName { get; set; }
        public int RoomType { get; set; }
        public int StarRate { get; set; }
        public int PackagePrice { get; set; }
        public string PackageStatus { get; set; }
        public string Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer_tbl> Customer_tbl { get; set; }
        public virtual HotelName_tbl HotelName_tbl { get; set; }
        public virtual PackageGroup_tbl PackageGroup_tbl { get; set; }
        public virtual StarRate_tbl StarRate_tbl { get; set; }
        public virtual PackageType_tbl PackageType_tbl { get; set; }
        public virtual RoomType_tbl RoomType_tbl { get; set; }
        public virtual TravelClass_tbl TravelClass_tbl { get; set; }
    }
}
