//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HajAndUmrah.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment_tbl
    {
        public int PaymentId { get; set; }
        public Nullable<int> Status { get; set; }
        public int CustomerId { get; set; }
    
        public virtual Customer_tbl Customer_tbl { get; set; }
    }
}
