//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HajAndUmrah.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_tbl
    {
        public int ServiceId { get; set; }
        public string AirlinesName { get; set; }
        public System.DateTime DepratureDate { get; set; }
        public System.TimeSpan DepratureTime { get; set; }
        public System.DateTime ArrivalDate { get; set; }
        public System.TimeSpan ArrivalTime { get; set; }
        public string BusName { get; set; }
        public System.DateTime BusDepratureDate { get; set; }
        public System.TimeSpan BusDepratureTime { get; set; }
        public System.DateTime BusArrivalDate { get; set; }
        public System.TimeSpan BusArrivalTime { get; set; }
        public int CustomerId { get; set; }
    
        public virtual Customer_tbl Customer_tbl { get; set; }
    }
}
